org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dhttp.keepAlive=false -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000 -Djdk.tls.client.protocols=TLSv1.2
android.useAndroidX=true
android.disallowKotlinSourceSets=false
kotlin.code.style=official
